export const mockListings = [
  {
    id: '1',
    title: 'Jollof Rice',
    emoji: '🍚',
    providerType: 'neighbor',
    providerName: 'Amara',
    area: 'Near Dorm 4',
    distance: '3 min walk',
    pickupWindow: 'Before 8:00 PM',
    pickupWindowEnd: 20,
    portions: 6,
    portionsLeft: 4,
    dietary: ['halal'],
    cuisine: 'West African',
    description: 'Homemade jollof rice with chicken. Made fresh this afternoon.',
    microwavable: true,
    allergens: [],
    prepDate: 'Today',
    pinX: 30,
    pinY: 38,
  },
  {
    id: '2',
    title: 'Veggie Buddha Bowls',
    emoji: '🥗',
    providerType: 'campus cafe',
    providerName: 'Green Bowl Cafe',
    area: 'Student Union, Ground Floor',
    distance: '5 min walk',
    pickupWindow: 'Before 7:30 PM',
    pickupWindowEnd: 19.5,
    portions: 8,
    portionsLeft: 8,
    dietary: ['vegan', 'gluten-free'],
    cuisine: 'Contemporary',
    description: 'End-of-day cafe surplus. Quinoa, roasted veggies, tahini, greens.',
    microwavable: true,
    allergens: ['sesame'],
    prepDate: 'Today',
    pinX: 62,
    pinY: 55,
  },
  {
    id: '3',
    title: 'Chicken Biryani',
    emoji: '🍛',
    providerType: 'neighbor',
    providerName: 'Priya',
    area: 'Graduate Housing',
    distance: '7 min walk',
    pickupWindow: 'Before 9:00 PM',
    pickupWindowEnd: 21,
    portions: 4,
    portionsLeft: 4,
    dietary: ['halal', 'gluten-free'],
    cuisine: 'South Asian',
    description: 'Made too much for family dinner. Fragrant, spiced, no pork.',
    microwavable: true,
    allergens: [],
    prepDate: 'Today',
    pinX: 73,
    pinY: 30,
  },
  {
    id: '4',
    title: 'Lentil Soup + Bread',
    emoji: '🍲',
    providerType: 'campus pantry',
    providerName: 'Campus Food Pantry',
    area: 'Wellness Center, Rm 102',
    distance: '8 min walk',
    pickupWindow: 'Before 6:00 PM',
    pickupWindowEnd: 18,
    portions: 12,
    portionsLeft: 12,
    dietary: ['vegan', 'halal'],
    cuisine: 'Mediterranean',
    description: 'Homemade red lentil soup and sourdough. Made by volunteer cooks.',
    microwavable: true,
    allergens: ['gluten (bread)'],
    prepDate: 'Today',
    pinX: 45,
    pinY: 72,
  },
  {
    id: '5',
    title: 'Baked Mac and Cheese',
    emoji: '🧀',
    providerType: 'campus org',
    providerName: 'Engineering Society',
    area: 'Engineering Building Lobby',
    distance: '10 min walk',
    pickupWindow: 'Before 8:30 PM',
    pickupWindowEnd: 20.5,
    portions: 15,
    portionsLeft: 9,
    dietary: ['vegetarian'],
    cuisine: 'American',
    description: 'Leftover from society meeting. Homestyle baked mac and cheese.',
    microwavable: true,
    allergens: ['dairy', 'gluten'],
    prepDate: 'Today',
    pinX: 55,
    pinY: 22,
  },
  {
    id: '6',
    title: 'Pita Wraps + Hummus',
    emoji: '🫓',
    providerType: 'campus org',
    providerName: 'Middle Eastern Cultural Society',
    area: 'Multicultural Center',
    distance: '4 min walk',
    pickupWindow: 'Before 7:00 PM',
    pickupWindowEnd: 19,
    portions: 10,
    portionsLeft: 6,
    dietary: ['halal', 'vegetarian'],
    cuisine: 'Middle Eastern',
    description: 'Pita wraps with hummus, falafel, cucumber, tomato. From our cultural event.',
    microwavable: false,
    allergens: ['gluten', 'sesame'],
    prepDate: 'Today',
    pinX: 38,
    pinY: 52,
  },
  {
    id: '7',
    title: 'Stir-Fry Noodles',
    emoji: '🍜',
    providerType: 'restaurant',
    providerName: 'Noodle House',
    area: 'Campus Food Court',
    distance: '6 min walk',
    pickupWindow: 'Before 9:30 PM',
    pickupWindowEnd: 21.5,
    portions: 5,
    portionsLeft: 5,
    dietary: [],
    cuisine: 'Asian Fusion',
    description: 'End-of-night kitchen surplus. Mixed vegetables and egg noodles.',
    microwavable: true,
    allergens: ['gluten', 'soy'],
    prepDate: 'Today',
    pinX: 80,
    pinY: 60,
  },
  {
    id: '8',
    title: 'Fresh Sourdough + Jam',
    emoji: '🍞',
    providerType: 'neighbor',
    providerName: 'Community Bakers Collective',
    area: 'West Campus Quad',
    distance: '12 min walk',
    pickupWindow: 'Before 10:00 PM',
    pickupWindowEnd: 22,
    portions: 3,
    portionsLeft: 3,
    dietary: ['vegetarian'],
    cuisine: 'Baked goods',
    description: 'Freshly baked sourdough from this morning. Available whole or sliced.',
    microwavable: false,
    allergens: ['gluten'],
    prepDate: 'Today',
    pinX: 18,
    pinY: 65,
  },
]

export const impactMessageTemplates = {
  rice: {
    headline: "Your jollof rice reached three students tonight.",
    body: "One of them mentioned it was the first home-cooked meal they'd had all week — they'd been running on vending machine food between back-to-back study sessions. What you made with care became someone else's warm dinner.",
  },
  biryani: {
    headline: "Your biryani made someone's evening.",
    body: "A graduate student who hadn't had a proper meal since the morning picked it up just before your deadline. They sent a thank-you that came through as a community rating. Small gesture, real impact.",
  },
  soup: {
    headline: "Your soup helped two families tonight.",
    body: "It went to a parent and a solo student who both came by the pantry within the hour. Warm, nourishing, and exactly what they needed. Thank you for making it.",
  },
  default: {
    headline: "Your food reached your community tonight.",
    body: "Someone nearby had a real meal because of what you shared. That kind of contribution — quiet, direct, and dignified — is exactly what Hearth is built on. Thank you.",
  },
}
